MACRO(FIND_PYTHON)
INCLUDE(FindPythonLibs)
IF (NOT ${PYTHONLIBS_FOUND} STREQUAL TRUE)
	MESSAGE(FATAL_ERROR "Python has not been found.")
ENDIF (NOT ${PYTHONLIBS_FOUND} STREQUAL TRUE)

INCLUDE(FindPythonInterp)
IF (NOT ${PYTHONINTERP_FOUND} STREQUAL TRUE)
	MESSAGE(FATAL_ERROR "Python executable has not been found.")
ENDIF (NOT ${PYTHONINTERP_FOUND} STREQUAL TRUE)

# Find PYTHON_LIBRARY_DIRS
GET_FILENAME_COMPONENT(PYTHON_LIBRARY_DIRS ${PYTHON_LIBRARIES} PATH)

EXECUTE_PROCESS(
  COMMAND "${PYTHON_EXECUTABLE}" "-c"
  "import sys, os; print os.sep.join(['lib', 'python' + sys.version[:3], 'site-packages'])"
  OUTPUT_VARIABLE PYTHON_SITELIB
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET)
ENDMACRO(FIND_PYTHON)

MACRO(INSTALL_PYTHON_MODULE DIRECTORY INSTALL_MODE PREFIX)
	INSTALL(CODE
		"EXECUTE_PROCESS(COMMAND
		\"${PYTHON_EXECUTABLE}\" setup.py ${INSTALL_MODE} --prefix=${PREFIX}
		WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${DIRECTORY})
		")
ENDMACRO(INSTALL_PYTHON_MODULE)
